/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LoginForm;

/**
 *
 * @author HP
 */
public class forgotpassword extends javax.swing.JFrame {

    /**
     * Creates new form forgotpassword
     */
    public forgotpassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtusername1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtusername2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblimg1 = new javax.swing.JLabel();
        resetpanel2 = new javax.swing.JPanel();
        lbltitle = new javax.swing.JLabel();
        lblreset = new javax.swing.JLabel();
        lblsetnewpass = new javax.swing.JLabel();
        txtsetnewpass = new javax.swing.JTextField();
        lblconfirmnewpass = new javax.swing.JLabel();
        txtconfirmnewpass = new javax.swing.JTextField();
        btnreset = new javax.swing.JButton();

        jLabel10.setFont(new java.awt.Font("Ravie", 3, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 0));
        jLabel10.setText("TIKOPAP");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Enter Email");

        txtusername1.setBackground(new java.awt.Color(0, 0, 0));
        txtusername1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtusername1.setForeground(new java.awt.Color(255, 255, 255));
        txtusername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusername1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Enter Preferred Username");

        txtusername2.setBackground(new java.awt.Color(0, 0, 0));
        txtusername2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtusername2.setForeground(new java.awt.Color(255, 255, 255));
        txtusername2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusername2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblimg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg3.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblimg1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblimg1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 520));

        resetpanel2.setBackground(new java.awt.Color(0, 0, 0));

        lbltitle.setFont(new java.awt.Font("Ravie", 3, 36)); // NOI18N
        lbltitle.setForeground(new java.awt.Color(204, 204, 0));
        lbltitle.setText("TIKOPAP");

        lblreset.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        lblreset.setForeground(new java.awt.Color(255, 255, 255));
        lblreset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblreset.setText("PASSWORD RESET");

        lblsetnewpass.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblsetnewpass.setForeground(new java.awt.Color(255, 255, 255));
        lblsetnewpass.setText("Enter New Password");

        txtsetnewpass.setBackground(new java.awt.Color(0, 0, 0));
        txtsetnewpass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtsetnewpass.setForeground(new java.awt.Color(255, 255, 255));
        txtsetnewpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsetnewpassActionPerformed(evt);
            }
        });

        lblconfirmnewpass.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblconfirmnewpass.setForeground(new java.awt.Color(255, 255, 255));
        lblconfirmnewpass.setText("Confirm New Password");

        txtconfirmnewpass.setBackground(new java.awt.Color(0, 0, 0));
        txtconfirmnewpass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtconfirmnewpass.setForeground(new java.awt.Color(255, 255, 255));
        txtconfirmnewpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconfirmnewpassActionPerformed(evt);
            }
        });

        btnreset.setBackground(new java.awt.Color(204, 204, 0));
        btnreset.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        btnreset.setForeground(new java.awt.Color(255, 255, 255));
        btnreset.setText("RESET");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout resetpanel2Layout = new javax.swing.GroupLayout(resetpanel2);
        resetpanel2.setLayout(resetpanel2Layout);
        resetpanel2Layout.setHorizontalGroup(
            resetpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resetpanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
            .addGroup(resetpanel2Layout.createSequentialGroup()
                .addGroup(resetpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resetpanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(resetpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(resetpanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(resetpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtsetnewpass, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblconfirmnewpass, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtconfirmnewpass, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblsetnewpass, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(resetpanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblreset, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        resetpanel2Layout.setVerticalGroup(
            resetpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetpanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblreset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblsetnewpass, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsetnewpass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblconfirmnewpass, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtconfirmnewpass, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        getContentPane().add(resetpanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 460, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtusername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusername1ActionPerformed

    private void txtusername2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusername2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusername2ActionPerformed

    private void txtsetnewpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsetnewpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsetnewpassActionPerformed

    private void txtconfirmnewpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconfirmnewpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconfirmnewpassActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        login lo = new login();
         lo.setVisible(true);
    }//GEN-LAST:event_btnresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgotpassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreset;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblconfirmnewpass;
    private javax.swing.JLabel lblimg1;
    private javax.swing.JLabel lblreset;
    private javax.swing.JLabel lblsetnewpass;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JPanel resetpanel2;
    private javax.swing.JTextField txtconfirmnewpass;
    private javax.swing.JTextField txtsetnewpass;
    private javax.swing.JTextField txtusername1;
    private javax.swing.JTextField txtusername2;
    // End of variables declaration//GEN-END:variables
}
