/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LoginForm;

import LoginForm.forgotpassword;
import Models.UserModel;
import LoginForm.signup;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import Service.UserService;
import javax.swing.JOptionPane;
import Utils.PasswordUtils;
import java.util.logging.Level;
import java.util.logging.Logger;
import Database.DatabaseOperations;
import Database.QueryBuilder;
import LessJava.*;

/**
 *
 * @author HP
 */
public class login extends javax.swing.JFrame {

    UserAuthenticator userAuthenticator = new UserAuthenticator();

    /**
     * Creates new form login
     */
    public login() {

        initComponents();
    }

    login(String slide_1) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        signupanel1 = new javax.swing.JPanel();
        lgnstmt1 = new javax.swing.JLabel();
        lgnstmt2 = new javax.swing.JLabel();
        lgnstmt3 = new javax.swing.JLabel();
        lgnstmt4 = new javax.swing.JLabel();
        signupaccess = new javax.swing.JButton();
        lbltitle3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblogin = new javax.swing.JLabel();
        lblenteruser = new javax.swing.JLabel();
        lblenterpass = new javax.swing.JLabel();
        btnlogin = new javax.swing.JButton();
        rembmrpass = new javax.swing.JCheckBox();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        forgotpassaccess = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel4.setBackground(new java.awt.Color(104, 104, 103));

        signupanel1.setBackground(new java.awt.Color(104, 104, 103));

        lgnstmt1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lgnstmt1.setForeground(new java.awt.Color(255, 255, 255));
        lgnstmt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnstmt1.setText("WELCOME!");

        lgnstmt2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lgnstmt2.setForeground(new java.awt.Color(255, 255, 255));
        lgnstmt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnstmt2.setText("Join the community and create an");
        lgnstmt2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lgnstmt3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lgnstmt3.setForeground(new java.awt.Color(255, 255, 255));
        lgnstmt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnstmt3.setText("account to unlock the full potential");

        lgnstmt4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lgnstmt4.setForeground(new java.awt.Color(255, 255, 255));
        lgnstmt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnstmt4.setText("of our platform");

        signupaccess.setBackground(new java.awt.Color(244, 239, 230));
        signupaccess.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        signupaccess.setForeground(new java.awt.Color(22, 42, 44));
        signupaccess.setText("SIGN UP");
        signupaccess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupaccessMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout signupanel1Layout = new javax.swing.GroupLayout(signupanel1);
        signupanel1.setLayout(signupanel1Layout);
        signupanel1Layout.setHorizontalGroup(
            signupanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupanel1Layout.createSequentialGroup()
                .addGroup(signupanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signupanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lgnstmt1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signupanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(signupanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lgnstmt3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lgnstmt2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(signupanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lgnstmt4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(signupanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(signupaccess, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        signupanel1Layout.setVerticalGroup(
            signupanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lgnstmt1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lgnstmt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lgnstmt3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lgnstmt4)
                .addGap(42, 42, 42)
                .addComponent(signupaccess)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        lbltitle3.setFont(new java.awt.Font("Algerian", 3, 48)); // NOI18N
        lbltitle3.setForeground(new java.awt.Color(22, 42, 44));
        lbltitle3.setText("TIKOPAP");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signupanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signupanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(244, 239, 230));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(94, 108, 91));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 6, 24, -1));

        lblogin.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        lblogin.setForeground(new java.awt.Color(94, 108, 91));
        lblogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblogin.setText("Login");
        jPanel2.add(lblogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 320, -1));

        lblenteruser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblenteruser.setForeground(new java.awt.Color(22, 42, 44));
        lblenteruser.setText("Username");
        jPanel2.add(lblenteruser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 89, 31));

        lblenterpass.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblenterpass.setForeground(new java.awt.Color(22, 42, 44));
        lblenterpass.setText("Password");
        jPanel2.add(lblenterpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 77, 26));

        btnlogin.setBackground(new java.awt.Color(214, 224, 226));
        btnlogin.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(94, 108, 91));
        btnlogin.setText("LOGIN");
        btnlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel2.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 199, 45));

        rembmrpass.setBackground(new java.awt.Color(244, 239, 230));
        rembmrpass.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        rembmrpass.setForeground(new java.awt.Color(94, 108, 91));
        rembmrpass.setText("Remember Password");
        rembmrpass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(rembmrpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 197, -1));

        txtusername.setBackground(new java.awt.Color(244, 239, 230));
        txtusername.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtusername.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 265, 32));

        txtpassword.setBackground(new java.awt.Color(244, 239, 230));
        txtpassword.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 265, 34));

        forgotpassaccess.setBackground(new java.awt.Color(244, 239, 230));
        forgotpassaccess.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        forgotpassaccess.setForeground(new java.awt.Color(94, 108, 91));
        forgotpassaccess.setText("Forgot Password?");
        forgotpassaccess.setBorder(null);
        forgotpassaccess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotpassaccessMouseClicked(evt);
            }
        });
        jPanel2.add(forgotpassaccess, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 110, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);

        setSize(new java.awt.Dimension(774, 468));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
   JOptionPane.showInputDialog(null, "You are successfuly logged in");
                                         
    }//GEN-LAST:event_btnloginActionPerformed

    private void signupaccessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupaccessMouseClicked
        signup si = new signup();
        si.setVisible(true);
    }//GEN-LAST:event_signupaccessMouseClicked

    private void forgotpassaccessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotpassaccessMouseClicked
      forgotpassword fo = new forgotpassword();
      fo.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_forgotpassaccessMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

<<<<<<< HEAD
=======
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void disableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disableMouseClicked
        txtpassword.setEchoChar((char) 0);
        disable.setVisible(false);
        disable.setEnabled(false);
        show.setEnabled(true);
        show.setEnabled(true);
    }//GEN-LAST:event_disableMouseClicked

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        txtpassword.setEchoChar((char) 0);
        disable.setVisible(true);
        disable.setEnabled(true);
        show.setEnabled(false);
        show.setEnabled(false);
    }//GEN-LAST:event_showMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String password = txtpassword.getText();
        String username = txtusername.getText();
        UserService userService = new UserService();
         userService.setCurrentUserByEmail("jesee@gmail.com");
         UserModel currentUser = userService.getCurrentUser();
        System.out.println("Current User: " + currentUser.getEmail());

        // Remove the current user from the session
        userService.removeCurrentUser();
        UserModel removedUser = userService.getCurrentUser();
        System.out.println("User after removal: " + removedUser);
        boolean isUserValid = userAuthenticator.CheckPasswordAndUserName(username, password);

        if (isUserValid) {
            JOptionPane.showMessageDialog(null, "You are successfully logged in");
        } else {
            JOptionPane.showMessageDialog(null, "Invalid username or password");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        signup si = new signup();

        si.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        forgotpassword fo = new forgotpassword();
        fo.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

>>>>>>> 57d4e6bf2cba74a6262e73d32b8109714569180f
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton forgotpassaccess;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblenterpass;
    private javax.swing.JLabel lblenteruser;
    private javax.swing.JLabel lblogin;
    private javax.swing.JLabel lbltitle3;
    private javax.swing.JLabel lgnstmt1;
    private javax.swing.JLabel lgnstmt2;
    private javax.swing.JLabel lgnstmt3;
    private javax.swing.JLabel lgnstmt4;
    private javax.swing.JCheckBox rembmrpass;
    private javax.swing.JButton signupaccess;
    private javax.swing.JPanel signupanel1;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
