/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginForm;

import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class logineo extends javax.swing.JFrame {

    /**
     * Creates new form logineo
     */
    public logineo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        signupanel1 = new javax.swing.JPanel();
        lgnstmt1 = new javax.swing.JLabel();
        lgnstmt2 = new javax.swing.JLabel();
        lgnstmt3 = new javax.swing.JLabel();
        lgnstmt4 = new javax.swing.JLabel();
        signupaccesseo = new javax.swing.JButton();
        lbltitle3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblogin = new javax.swing.JLabel();
        lblenteruser = new javax.swing.JLabel();
        lblenterpass = new javax.swing.JLabel();
        btnlogineo = new javax.swing.JButton();
        rembmrpass = new javax.swing.JCheckBox();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        forgotpassaccesseo = new javax.swing.JButton();
        disable = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        show = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(104, 104, 103));

        signupanel1.setBackground(new java.awt.Color(104, 104, 103));

        lgnstmt1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lgnstmt1.setForeground(new java.awt.Color(255, 255, 255));
        lgnstmt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnstmt1.setText("WELCOME!");

        lgnstmt2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lgnstmt2.setForeground(new java.awt.Color(255, 255, 255));
        lgnstmt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnstmt2.setText("Join the community and create an");
        lgnstmt2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lgnstmt3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lgnstmt3.setForeground(new java.awt.Color(255, 255, 255));
        lgnstmt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnstmt3.setText("account to unlock the full potential");

        lgnstmt4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lgnstmt4.setForeground(new java.awt.Color(255, 255, 255));
        lgnstmt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnstmt4.setText("of our platform");

        signupaccesseo.setBackground(new java.awt.Color(244, 239, 230));
        signupaccesseo.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        signupaccesseo.setForeground(new java.awt.Color(22, 42, 44));
        signupaccesseo.setText("SIGN UP");
        signupaccesseo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupaccesseoMouseClicked(evt);
            }
        });
        signupaccesseo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupaccesseoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signupanel1Layout = new javax.swing.GroupLayout(signupanel1);
        signupanel1.setLayout(signupanel1Layout);
        signupanel1Layout.setHorizontalGroup(
            signupanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupanel1Layout.createSequentialGroup()
                .addGroup(signupanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signupanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lgnstmt1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signupanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(signupanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lgnstmt3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lgnstmt2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(signupanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lgnstmt4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(signupanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(signupaccesseo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        signupanel1Layout.setVerticalGroup(
            signupanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lgnstmt1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lgnstmt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lgnstmt3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lgnstmt4)
                .addGap(42, 42, 42)
                .addComponent(signupaccesseo)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        lbltitle3.setFont(new java.awt.Font("Algerian", 3, 48)); // NOI18N
        lbltitle3.setForeground(new java.awt.Color(22, 42, 44));
        lbltitle3.setText("TIKOPAP");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signupanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signupanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(244, 239, 230));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblogin.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        lblogin.setForeground(new java.awt.Color(94, 108, 91));
        lblogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblogin.setText("Login");
        jPanel2.add(lblogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 320, -1));

        lblenteruser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblenteruser.setForeground(new java.awt.Color(22, 42, 44));
        lblenteruser.setText("Username");
        jPanel2.add(lblenteruser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 89, 31));

        lblenterpass.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblenterpass.setForeground(new java.awt.Color(22, 42, 44));
        lblenterpass.setText("Password");
        jPanel2.add(lblenterpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 77, 26));

        btnlogineo.setBackground(new java.awt.Color(214, 224, 226));
        btnlogineo.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        btnlogineo.setForeground(new java.awt.Color(94, 108, 91));
        btnlogineo.setText("LOGIN");
        btnlogineo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogineo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogineoActionPerformed(evt);
            }
        });
        jPanel2.add(btnlogineo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 199, 45));

        rembmrpass.setBackground(new java.awt.Color(244, 239, 230));
        rembmrpass.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        rembmrpass.setForeground(new java.awt.Color(94, 108, 91));
        rembmrpass.setText("Remember Password");
        rembmrpass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(rembmrpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 197, -1));

        txtusername.setBackground(new java.awt.Color(244, 239, 230));
        txtusername.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtusername.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 265, 32));

        txtpassword.setBackground(new java.awt.Color(244, 239, 230));
        txtpassword.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 265, 34));

        forgotpassaccesseo.setBackground(new java.awt.Color(244, 239, 230));
        forgotpassaccesseo.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        forgotpassaccesseo.setForeground(new java.awt.Color(94, 108, 91));
        forgotpassaccesseo.setText("Forgot Password?");
        forgotpassaccesseo.setBorder(null);
        forgotpassaccesseo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotpassaccesseoMouseClicked(evt);
            }
        });
        forgotpassaccesseo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotpassaccesseoActionPerformed(evt);
            }
        });
        jPanel2.add(forgotpassaccesseo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 110, 30));

        disable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-invisible-20 (1).png"))); // NOI18N
        jPanel2.add(disable, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 30, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-person-20.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 186, 30, 20));

        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-eye-20 (2).png"))); // NOI18N
        jPanel2.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 30, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupaccesseoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupaccesseoMouseClicked
        signup si = new signup();
        si.setVisible(true);
    }//GEN-LAST:event_signupaccesseoMouseClicked

    private void btnlogineoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogineoActionPerformed
        JOptionPane.showInputDialog(null, "You are successfuly logged in");

    }//GEN-LAST:event_btnlogineoActionPerformed

    private void forgotpassaccesseoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotpassaccesseoMouseClicked
        forgotpassword fo = new forgotpassword();
        fo.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_forgotpassaccesseoMouseClicked

    private void signupaccesseoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupaccesseoActionPerformed
        signupeo se = new signupeo();

        se.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_signupaccesseoActionPerformed

    private void forgotpassaccesseoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotpassaccesseoActionPerformed
        forgotpassword fo = new forgotpassword();
        fo.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_forgotpassaccesseoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logineo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logineo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logineo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logineo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logineo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogineo;
    private javax.swing.JLabel disable;
    private javax.swing.JButton forgotpassaccesseo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblenterpass;
    private javax.swing.JLabel lblenteruser;
    private javax.swing.JLabel lblogin;
    private javax.swing.JLabel lbltitle3;
    private javax.swing.JLabel lgnstmt1;
    private javax.swing.JLabel lgnstmt2;
    private javax.swing.JLabel lgnstmt3;
    private javax.swing.JLabel lgnstmt4;
    private javax.swing.JCheckBox rembmrpass;
    private javax.swing.JLabel show;
    private javax.swing.JButton signupaccesseo;
    private javax.swing.JPanel signupanel1;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
